apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels: { app: api }
spec:
  type: ClusterIP
  selector: { app: api }
  ports: [{ port: 3001, targetPort: {{ .Values.api.port }} }]
